### ISSUE TITLE
Duplicate Symbols in Muti Object Projects

### ISSUE THREAD

**Issue by beachtom** [tomvandig/fuzzy-bools#2]
Hi,

When building in a project with multiple object files using the library leads to duplicate symbol errors. I think the symbols that are designed to be exported to be used need to be marked as inline.

**Comment by tomvandig** [comment]
@beachtom should be fixed now, only remaining duplicate symbol issues are inside cdt

**Comment by beachtom** [comment]
Great! Thanks all working now
